# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 3
        fairness: 3
        explainable: 3
        Interpretability: 2
        human-in-the-loop: 3
        machine teaching: 3
        bias: 1

# 通知の閾値
score_threshold: 0
